before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test

Build the code:
  stage: build
  image: openjdk:8
  script: ./gradlew assemble

Tests:
  stage: test
  image: openjdk:8
  script: ./gradlew check

